site_name: Ansari
site_url: https://ansari.chat/docs
nav:
  - Home: index.md
  - What Ansari can do: capabilities.md
  - Validation: 
    - Validating correctness: validation.md
    - Ramadan Validation: ramadan-results.md
  - FAQ: faq.md
  - Additional material: material.md

theme: readthedocs

